node('maven') {
  stage('Build App') {
    git url: "https://github.com/Mjacks3/java_x_jenkins_x_openshift_example.git"
    sh 'mvn -B -DskipTests clean package'
  }

  stage('Test App') {
   sh 'mvn test'
   junit 'target/surefire-reports/*.xml'
  }

  stage('Deploy App') {
   sh 'oc login https://console.okd.sl.cloud9.ibm.com:8443 --token=GUH8GL_9G3bHdXAgYFToIM8mjvqwOkJjPPNcIWPqnjM'
   sh 'oc project bar'
   sh 'oc new-app --name=Demo_APP_B  wildfly~https://github.com/Mjacks3/java_x_jenkins_x_openshift_example.git'
   sh 'oc deploy --latest dc/bar'
   sh 'oc scale dc bar --replicas=3'
  }

}