node('maven') {
  stage('Build App') {
    git url: "https://github.com/Mjacks3/java_x_jenkins_x_openshift_example.git"
    sh 'mvn -B -DskipTests clean package'
  }

  stage('Test App') {
   sh 'mvn test'
   junit 'target/surefire-reports/*.xml'
  }

  stage('Deploy App') {
   sh 'oc login https://console.okd.sl.cloud9.ibm.com:8443 --certificate-authority --token=GUH8GL_9G3bHdXAgYFToIM8mjvqwOkJjPPNcIWPqnjM'
   sh 'oc project bar'
   sh 'oc new-app --name=demo-app-c  wildfly~https://github.com/Mjacks3/java_x_jenkins_x_openshift_example.git'
   sh 'oc rollout demo-app-c'
   sh 'oc expose svc/demo-app-b'
   sh 'oc scale svc/demo-app-b --replicas=3'

  }
}